// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wwfoicofumfrtmyzehso.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind3Zm9pY29mdW1mcnRteXplaHNvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0NzAzOTEsImV4cCI6MjA3MDA0NjM5MX0.D25Li6snooP8u-9lrgIhrQQb0LjdCW2XXnnud-KlmVc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});